"""Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms."""

from datetime import datetime
startTime = datetime.now()

def fib(n):
    if n == 1:
        return 1
    if n == 2:
        return 1 + fib(n-1)
    else:
        return fib(n-1) + fib(n-2)
#slow

x = 0
n = 1
while x < 4000000:
    new = fib(n)
    if new % 2 == 0:
        x += new
    else:
        pass
    n += 1
print x

print datetime.now() - startTime

#faster

startTime = datetime.now()

a = b = fib(1)
c = a + b
sum = c

while sum < 4000000:
    a = b+c
    b=c+a
    c = a+b
    sum+=c
print sum

print datetime.now() - startTime